
name: test-workflow-1
on: workflow-dispatch
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: Execute the command
      run: echo "Welcome"
  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
    - name: Execute the below commands
      run: |
        hostname -s
        echo "Thank you"
